env:
  es2024: true
extends:
  - eslint:recommended
overrides:
  - extends: ./.eslintrc.react.yml
    files:
      - '**.*.jsx'
      - '**.*.tsx'
  - extends: ./.eslintrc.typescript.yml
    files:
      - '**/*.ts'
      - '**/*.tsx'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
root: true
rules:
  no-empty:
    - error
    - allowEmptyCatch: true
  prettier/prettier: error
