name: Static code analysis

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# Allow one concurrent deployment
concurrency:
  group: 'static-code-analysis'
  cancel-in-progress: true

jobs:
  precommit:
    if: (!startsWith(github.repository, 'compulim/template-'))
    name: Precommit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm clean-install

      - run: npm run build

      - run: npm run precommit
